export const languages = [
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Bahasa Melayu' },
  { code: 'ca', name: 'Català' },
  { code: 'da', name: 'Dansk' },
  { code: 'de', name: 'Deutsch' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'el', name: 'Eλληνικά' },
  { code: 'fr', name: 'Français' },
  { code: 'hr', name: 'Hrvatski' },
  { code: 'it', name: 'Italiano' },
  { code: 'hu', name: 'Magyar' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'no', name: 'Norsk' },
  { code: 'pl', name: 'Polski' },
  { code: 'pt', name: 'Português' },
  { code: 'fi', name: 'Suomi' },
  { code: 'sv', name: 'Svenska' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'is', name: 'Íslenska' },
  { code: 'cs', name: 'Čeština' },
  { code: 'ru', name: 'Русский' },
  { code: 'th', name: 'ภาษาไทย' },
  { code: 'zh', name: '中文 (简体)' },
  { code: 'zh-TW', name: '中文 (繁體)' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' }
]

export const currencies = [
  { code: 'ARS', name: 'Argentine peso' },
  { code: 'AUD', name: 'Australian dollar' },
  { code: 'BRL', name: 'Brazilian real' },
  { code: 'BGN', name: 'Bulgarian lev' },
  { code: 'CAD', name: 'Canadian dollar' },
  { code: 'CLP', name: 'Chilean peso' },
  { code: 'CNY', name: 'Chinese yuan' },
  { code: 'COP', name: 'Colombian peso' },
  { code: 'CRC', name: 'Costa Rican colon' },
  { code: 'HRK', name: 'Croatian kuna' },
  { code: 'CZK', name: 'Czech koruna' },
  { code: 'DKK', name: 'Danish krone' },
  { code: 'AED', name: 'Emirati dirham' },
  { code: 'EUR', name: 'Euro' },
  { code: 'HKD', name: 'Hong Kong dollar' },
  { code: 'HUF', name: 'Hungarian forint' },
  { code: 'INR', name: 'Indian rupee' },
  { code: 'ILS', name: 'Israeli new shekel' },
  { code: 'JPY', name: 'Japanese yen' },
  { code: 'MYR', name: 'Malaysian ringgit' },
  { code: 'MXN', name: 'Mexican peso' },
  { code: 'MAD', name: 'Moroccan dirham' },
  { code: 'TWD', name: 'New Taiwan dollar' },
  { code: 'NZD', name: 'New Zealand dollar' },
  { code: 'NOK', name: 'Norwegian krone' },
  { code: 'PEN', name: 'Peruvian sol' },
  { code: 'PHP', name: 'Philippine peso' },
  { code: 'PLN', name: 'Polish zloty' },
  { code: 'GBP', name: 'Pound sterling' },
  { code: 'RON', name: 'Romanian leu' },
  { code: 'RUB', name: 'Russian ruble' },
  { code: 'SAR', name: 'Saudi Arabian riyal' },
  { code: 'SGD', name: 'Singapore dollar' },
  { code: 'ZAR', name: 'South African rand' },
  { code: 'KRW', name: 'South Korean won' },
  { code: 'SEK', name: 'Swedish krona' },
  { code: 'CHF', name: 'Swiss franc' },
  { code: 'THB', name: 'Thai baht' },
  { code: 'TRY', name: 'Turkish lira' },
  { code: 'USD', name: 'United States dollar' },
  { code: 'UYU', name: 'Uruguayan peso' }
]
